### ISSUE TITLE
Is there event add/edit functionality with database support ?

### ISSUE THREAD

**Issue by prakashmalviya** [Arkhas/Laravel5Calendar#1]
Hi,

I have checked many of the calendar packages on laravel but none of them have event add/edit functionality dynamically with database support.

Is there your package support for the same ?

Thanks,

**Comment by Arkhas** [comment]
No, this is just for display only, but with a bit of ajax, I think it would be quick to implement it :)

**Comment by prakashmalviya** [comment]
Ok, I will implement it.

Thanks..
