### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by nickescobedo** [Arkhas/Laravel5Calendar#5]
Laravel 5.5 now has package discovery to automatically register facades and service providers.
https://laravel.com/docs/5.5/packages#package-discovery

Also since maybe Laravel 5? registering service providers no longer uses: `$this->app->share` and should use `$this->app->singleton` instead. I got an error with a 5.5 project that I pulled it in on. https://laravel.com/docs/5.5/providers#the-register-method

I have made the above changes in my branch: https://github.com/nickescobedo/Laravel5Calendar/commits/composer-updates

I didn't create a pull request yet for it because I'm not sure if it breaks existing projects. If it does then I suggest creating a branch from master for older projects and then my updated code could be merged in if you wanted it.

**Comment by Arkhas** [comment]
I just created a new branch called laravel-5.4 for the old one.

If you submit your pull request, I will pass the master on 5.5 and create a new release version (2.0.0) so existing project won't break :)

Thank you for your work
