### ISSUE TITLE
Small mistake when the month is February and today is 29

### ISSUE THREAD

**Issue by dpmontero** [Arkhas/Laravel5Calendar#9]
Hi,

I found a small problem when the date of the day does not exist as in the month of February. For example, today is November 29, if you push the next month jumps the month of February.

It seems that I have found the solution, just add the first day of the month to the date of the current month:
src/Calendar.php (line 55)
`
$current_month = Carbon::createFromDate($year, $month, 1);
`

Thank you!

**Comment by Arkhas** [comment]
Thank you for your report :)
